#ifndef A_A_HPP
#define A_A_HPP

#define TEMPLATE_ARG_1(T, N) T##N
#define TEMPLATE_ARG_2(T) TEMPLATE_ARG_1(T, 1), TEMPLATE_ARG_1(T, 2)
#define TEMPLATE_ARG_3(T) TEMPLATE_ARG_2(T), TEMPLATE_ARG_1(T, 3)
#define TEMPLATE_ARG_4(T) TEMPLATE_ARG_3(T), TEMPLATE_ARG_1(T, 4)
#define TEMPLATE_ARG_5(T) TEMPLATE_ARG_4(T), TEMPLATE_ARG_1(T, 5)
#define TEMPLATE_ARG_6(T) TEMPLATE_ARG_5(T), TEMPLATE_ARG_1(T, 6)
#define TEMPLATE_ARG_7(T) TEMPLATE_ARG_6(T), TEMPLATE_ARG_1(T, 7)
#define TEMPLATE_ARG_8(T) TEMPLATE_ARG_7(T), TEMPLATE_ARG_1(T, 8)
#define TEMPLATE_ARG_9(T) TEMPLATE_ARG_8(T), TEMPLATE_ARG_1(T, 9)
#define TEMPLATE_ARG(ARGT, ARGN) TEMPLATE_ARG_##ARGN(ARGT)

//用于防止函数调用的时候有隐式转换，作用类似explicit，但是explicit只能修饰构造和析构函数
#define EXPLICIT(RETURN, FUNCTION, ARGN) template<TEMPLATE_ARG(class T, ARGN)> RETURN FUNCTION(TEMPLATE_ARG(T, ARGN)) = delete;


#endif // A_A_HPP
