#ifndef COMMONTOOL_GLOBAL_H
#define COMMONTOOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMONTOOL_LIBRARY)
#  define COMMONTOOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMMONTOOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMONTOOL_GLOBAL_H
